mysite/m7_python/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from .views import index, register, complement, users_intro, profile_update, add_property, property_update, property_delete

app_name = 'm7_python'

urlpatterns = [
    # example: /
    path('', index, name = 'principal'),
    # example: /dashboard/
    path('dashboard/', users_intro, name = 'panel'),
    # example: /login/
    path('login/', LoginView.as_view(next_page = 'm7_python:panel'), name = 'iniciar'),
    # example: /logout/
    path('logout/', LogoutView.as_view(next_page = 'm7_python:principal'), name = 'cerrar'),
    # example: /register/
    path('register/', register, name = 'registrarse'),
    # example: /complement/
    path('complement/', complement, name = 'complemento'),
    # example: /update/
    path('update/', profile_update, name = 'actualizarse'),
    # example: /add_new/
    path('add_new/', add_property, name = 'agrégala'),
    # example: /update_prop/
    path('update_prop/', property_update, name = 'actualízalo'),
    # example: /delete_prop/
    path('delete_prop/', property_delete, name = 'elimínala'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('m7_python.urls'))
]

mysite/m7_python/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from m7_python.models import Profile, Comuna, Region, Inmueble


class UserForm(UserCreationForm):
    rut = forms.CharField(
        max_length = 10,
        label = 'RUT',
        widget = forms.TextInput(attrs = {'class': 'form-control', 'placeholder': 'Ex: 12345678-9'}))
    email = forms.EmailField(
        max_length = 50,
        label = 'Correo electrónico',
        widget = forms.EmailInput(attrs = {'class': 'form-control', 'placeholder': 'Ex: micorreo@electronico.com'}))
    password1 = forms.CharField(
        label = 'Contraseña',
        widget = forms.PasswordInput(attrs = {'class': 'form-control', 'placeholder': '8 caracteres mínimo'}))
    password2 = forms.CharField(
        label = 'Reingresa tu contraseña',
        widget = forms.PasswordInput(attrs = {'class': 'form-control', 'placeholder': '8 caracteres mínimo'}))

    class Meta(UserCreationForm.Meta):
        model = Profile
        fields = ('rut', 'email', 'password1', 'password2')


class CompletingUserForm(forms.Form):
    TYPE_USER = (
        (1, 'Arrendatario'),
        (2, 'Arrendador'))

    first_name = forms.CharField(
        max_length = 50,
        label = 'Nombres',
        widget = forms.TextInput(attrs = {'class': 'form-control', 'placeholder': 'Ex: Juanín Juanoso'}))
    last_name = forms.CharField(
        max_length = 50,
        label = 'Apellidos',
        widget = forms.TextInput(attrs = {'class': 'form-control', 'placeholder': 'Ex: Pérez Pereira'}))
    type_user = forms.CharField(
        label = 'Tipo de usuario',
        widget = forms.Select(attrs = {'class': 'form-control'}, choices = TYPE_USER))
    adress = forms.CharField(
        max_length = 100,
        label = 'Dirección',
        widget = forms.TextInput(attrs = {'class': 'form-control', 'placeholder': 'Calle, número, departamento, ciudad.'}))
    phone_number = forms.CharField(
        max_length = 9,
        label = 'Teléfono de contacto',
        widget = forms.TextInput(attrs = {'class': 'form-control', 'placeholder': 'Ex: 987654321'}))
    picture = forms.URLField(
        required = False,
        label = 'Foto personal',
        widget = forms.URLInput(attrs = {'class': 'form-control', 'placeholder': 'Ex: http://mi.foto.com'}))


class UserUpdateForm(forms.ModelForm):
    picture = forms.URLField(
        required = False,
        label = 'Foto personal',
        widget = forms.URLInput(attrs = {'class': 'form-control', 'placeholder': 'Ex: http://mi.foto.com'}))

    class Meta:
        model = Profile
        fields = (
            'first_name',
            'last_name',
            'email',
            'adress',
            'phone_number',
            'picture',
            )
        labels = {
            'first_name': "Nombres",
            'last_name': "Apellidos",
            'email': "Correo electrónico",
            'adress': "Dirección",
            'phone_number': "Teléfono de contacto",
        }
        widgets = {
            'first_name': forms.TextInput(attrs = {'class': 'form-control'}),
            'last_name': forms.TextInput(attrs = {'class': 'form-control'}),
            'email': forms.EmailInput(attrs = {'class': 'form-control'}),
            'adress': forms.TextInput(attrs = {'class': 'form-control'}),
            'phone_number': forms.TextInput(attrs = {'class': 'form-control'}),
        }


class InmuebleForm(forms.Form):
    TYPE_PROPERTY = (
        (1, 'Casa'),
        (2, 'Departamento'),
        (3, 'Parcela'),
        (4, 'Estacionamiento'),
        (5, 'Otro'))
    MUNICIPALITY = [(comuna.id, comuna.municipality) for comuna in Comuna.objects.all().order_by('municipality')]
    REGION = [(region.id, region.region) for region in Region.objects.all()]

    name = forms.CharField(
        max_length = 100,
        label = 'Nombre de la publicación',
        widget = forms.TextInput(attrs = {
            'class': 'form-control',
            'placeholder': 'Un espeluznante y atractivo resumen en 100 caracteres.'}))
    description = forms.CharField(
        max_length = 500,
        label = 'Descripción de la propiedad',
        widget = forms.Textarea(attrs = {
            'class': 'form-control',
            'style': 'resize: none;',
            'rows': '6',
            'placeholder': 'Tu inmueble en 500 caracteres.'}))
    tipo_inmueble = forms.CharField(
        label = 'Tipo de inmueble',
        widget = forms.Select(attrs = {'class': 'form-control'}, choices = TYPE_PROPERTY))
    builded_sqm = forms.IntegerField(
        label = 'M2 construidos',
        min_value = 0,
        widget = forms.NumberInput(attrs = {'class': 'form-control'}))
    terrain_sqm = forms.IntegerField(
        label = 'M2 del terreno',
        min_value = 0,
        widget = forms.NumberInput(attrs = {'class': 'form-control'}))
    parkings = forms.IntegerField(
        label = 'Estacionamientos',
        min_value = 0,
        widget = forms.NumberInput(attrs = {'class': 'form-control'}))
    rooms = forms.IntegerField(
        label = 'Habitaciones',
        min_value = 0,
        widget = forms.NumberInput(attrs = {'class': 'form-control'}))
    bathrooms = forms.IntegerField(
        label = 'Baños',
        min_value = 0,
        widget = forms.NumberInput(attrs = {'class': 'form-control'}))
    rent_price = forms.FloatField(
        label = 'Precio del arriendo mensual',
        min_value = 0,
        widget = forms.NumberInput(attrs = {'class': 'form-control'}))
    adress = forms.CharField(
        max_length = 100,
        label = 'Dirección',
        widget = forms.TextInput(attrs = {'class': 'form-control', 'placeholder': 'Calle, número, departamento, otro.'}))
    region = forms.CharField(
        label = 'Región',
        widget = forms.Select(attrs = {'class': 'form-control'}, choices = REGION))
    comuna = forms.CharField(
        label = 'Comuna',
        widget = forms.Select(attrs = {'class': 'form-control'}, choices = MUNICIPALITY))


class InmuebleUpdateForm(forms.ModelForm):
    class Meta:
        model = Inmueble
        fields= (
            'name',
            'description',
            'builded_sqm',
            'terrain_sqm',
            'rooms',
            'bathrooms',
            'parkings',
            'rent_price',
        )
        labels = {
            'name': 'Nombre de la publicación',
            'description': 'Descripción de la propiedad',
            'builded_sqm': 'M2 construidos',
            'terrain_sqm': 'M2 del terreno',
            'rooms': 'Habitaciones',
            'bathrooms': 'Baños',
            'parkings': 'Estacionamientos',
            'rent_price': 'Precio del arriendo mensual',
        }
        widgets = {
            'name': forms.TextInput(attrs = {'class': 'form-control'}),
            'description': forms.Textarea(attrs = {
                'class': 'form-control',
                'style': 'resize: none;',
                'rows': '6'}),            
            'builded_sqm': forms.NumberInput(attrs = {'class': 'form-control'}),
            'terrain_sqm': forms.NumberInput(attrs = {'class': 'form-control'}),
            'rooms': forms.NumberInput(attrs = {'class': 'form-control'}),
            'bathrooms': forms.NumberInput(attrs = {'class': 'form-control'}),
            'parkings': forms.NumberInput(attrs = {'class': 'form-control'}),
            'rent_price': forms.NumberInput(attrs = {'class': 'form-control'}),
        }

mysite/m7_python/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from m7_python.models import Profile, TipoUser, Inmueble, TipoInmueble, Comuna, Region
from m7_python.forms import UserForm, CompletingUserForm, UserUpdateForm, InmuebleForm, InmuebleUpdateForm

def index(request):
    return render(request, './m7_python/index.html', {})

@login_required
def users_intro(request):
    usuario = request.user
    sapo = True
    if usuario.tipo_user_id == 1:
        inmuebles = Inmueble.objects.filter(user = usuario)
    else:
        inmuebles = Inmueble.objects.all()
    if len(inmuebles) == 0:
        sapo = False
    return render(request, './m7_python/dashboard.html', {'properties': inmuebles, 'checker': sapo})

def register(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            # Una vez creado el usuario exitosamente, se le envía a completar el registro.
            return HttpResponseRedirect(
                '/complement?user=' + str(form.cleaned_data['rut'])
                )
    else:
        form = UserForm()
    return render(request, './registration/register.html', {'formulario': form})

def complement(request):
    rut = request.GET['user']
    if request.method == 'POST':
        form = CompletingUserForm(request.POST)
        if form.is_valid():
            # Se extraen los datos del 'request' para actualizar la información del usuario.
            user = Profile.objects.get(rut = rut)
            user.first_name = form.cleaned_data['first_name']
            user.last_name = form.cleaned_data['last_name']
            user.tipo_user = TipoUser.objects.get(pk = int(form.cleaned_data['type_user']))
            user.adress = form.cleaned_data['adress']
            user.phone_number = form.cleaned_data['phone_number']
            user.picture = form.cleaned_data['picture']
            user.save()
            messages.success(request, f'El usuario {user.first_name} ha sido creado exitosamente.')
            return HttpResponseRedirect('/login')
    else:
        form = CompletingUserForm()
    return render(request, './registration/complement.html', {'formulario': form})

@login_required
def profile_update(request):
    if request.method == 'POST':
        form = UserUpdateForm(request.POST, instance = request.user)
        if form.is_valid():
            form.save()
            messages.success(request, f'Los datos del usuario{form.cleaned_data["first_name"]} han sido actualizados exitosamente.')
            return HttpResponseRedirect('/dashboard')
    else:
        # 'instance=' permite que los campos no estén vacíos al momento de actualizar.
        form = UserUpdateForm(instance = request.user)
    return render(request, './registration/update_profile.html', {'formulario': form})

@login_required
def add_property(request):
    if request.method == 'POST':
        form = InmuebleForm(request.POST)
        if form.is_valid():
            user = request.user
            name = form.cleaned_data['name']
            description = form.cleaned_data['description']
            builded_sqm = form.cleaned_data['builded_sqm']
            terrain_sqm = form.cleaned_data['terrain_sqm']
            parkings = form.cleaned_data['parkings']
            rooms = form.cleaned_data['rooms']
            bathrooms = form.cleaned_data['bathrooms']
            adress = form.cleaned_data['adress']
            rent_price = form.cleaned_data['rent_price']
            tipo_inmueble = TipoInmueble.objects.get(pk = int(form.cleaned_data['tipo_inmueble']))
            comuna = Comuna.objects.get(pk = int(form.cleaned_data['comuna']))
            region = Region.objects.get(pk = int(form.cleaned_data['region']))

            Inmueble.objects.create(
                user = user,
                name = name,
                description = description,
                builded_sqm = builded_sqm,
                terrain_sqm = terrain_sqm,
                parkings = parkings,
                rooms = rooms,
                bathrooms = bathrooms,
                adress = adress,
                rent_price = rent_price,
                tipo_inmueble = tipo_inmueble,
                comuna = comuna,
                region = region,
            )
            messages.success(request, 'El inmueble ha sido agregado exitosamente.')
            return HttpResponseRedirect('/dashboard')
    else:
        form = InmuebleForm()
    return render(request, './m7_python/add_property.html', {'formulario': form})

@login_required
def property_update(request):
    property = Inmueble.objects.get(id = request.GET['id'])
    if request.method == 'POST':
        form = InmuebleUpdateForm(request.POST, instance = property)
        if form.is_valid():
            form.save()
            messages.success(request, 'Los datos de su propiedad han sido actualizados exitosamente.')
            return HttpResponseRedirect('/dashboard')
    else:
        form = InmuebleUpdateForm(instance = property)
    return render(request, './registration/update_property.html', {'formulario': form, 'propiedad': property})

@login_required
def property_delete(request):
    property = Inmueble.objects.get(id = request.GET['id'])
    property.delete()
    messages.success(request, 'Los datos de su propiedad han sido eliminados.')
    return HttpResponseRedirect('/dashboard')

mysite/m7_python/templates/m7_python/add_property.html
{% extends 'm7_python/base.html' %}

{% block main %}
<main class="container my-3">
    <div class="row">
        <h1 class="mb-4 col-12 text-center">Agrega un nuevo inmueble:</h1>
        <form action="" method="post" class="mx-auto fs-4 col-12 col-md-10">
            {% csrf_token %}
            {{ formulario.as_p }}
            <div class="text-center">
                <button class="btn btn-haunted my-2 fs-4">Agregar</button>
            </div>
        </form>
    </div>
</main>
{% endblock main %}

mysite/m7_python/templates/m7_python/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es" dir="ltr">

<head>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!--Etiqueta necesaria para la responsividad.-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <!--Link para habilitar la hoja de estilos CSS de Bootstrap v5.1.3, minificado, por CDN.-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!--Link para habilitar las fuentes de Google Fonts.-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <!--URL de la fuente específica que se necesita.-->
    <link href="https://fonts.googleapis.com/css2?family=Creepster&family=Noto+Sans+Display:wght@300;400;600&family=Oswald&display=swap" rel="stylesheet">     <!--Link para habilitar los íconos de Font Awesome Free v6.1.0, por CDN.-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.0/css/all.css"
        integrity="sha384-eLT4eRYPHTmTsFGFAzjcCWX+wHfUInVWNm9YnwpiatljsZOwXtwV2Hh6sHM6zZD9"
        crossorigin="anonymous"/>
    <!--Link para referenciar la hoja de estilos CSS local.-->
    <link rel="stylesheet" href="{% static './m7_python/css/style.css' %}">
    <!--Etiquetas para el title de la pestaña y el favicon.-->
    <title>HauntedHouses</title>
    <link rel="shortcut icon" type="image/png" href="{% static './m7_python/img/haunted_house.png' %}">
    <!--<meta> informativos para que tu página sea fácil de encontrar por los buscadores.-->
    <meta name="author" content="Néstor Patricio">
    <meta name="description" content="Discover spooky houses for rent">
    <meta name="keywords" content="haunted houses rent spooky">

</head>

<body>
    {% block header %}
    {% include 'm7_python/header.html' %}
    {% endblock header %}

    {% block nav %}
    {% include 'm7_python/nav.html' %}
    {% endblock nav %}

    {% block main %}
    <div class="container">
        <h1>Sitio en construcción.</h1>
    </div>
    {% endblock main %}

    {% block footer %}
    {% include 'm7_python/footer.html' %}
    {% endblock footer %}

    <!--Link para habilitar el script JS de JQuery v3.6.0, minificado y con Ajax y módulos effects, por CDN.-->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <!--Link para habilitar el script JS de Bootstrap v5.1.3, minificado y con Popper, por CDN.-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
    <!--Link para referenciar el script JS local.-->
    <script src="{% static './m7_python/js/script.js' %}"></script>

</body>

</html>

mysite/m7_python/templates/m7_python/dashboard.html
{% extends 'm7_python/base.html' %}

{% block main %}
<main class="container my-3">

{% if messages %}
    {% for message in messages %}
    <div class="alert message alert-dismissible fade show display-6 text-center" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" style="color: white;" aria-label="Close"></button>
    </div>
    {% endfor %}
{% endif %}

{% if user.is_authenticated %}
    {% if user.tipo_user_id == 1 %}

    <div class="row">
        <div class="col-12 col-md-4 col-lg-3 col-xl-2">
            <img class="img-fluid rounded" src="{{ user.picture }}" alt="{{ user.first_name }}">
        </div>
        <div class="col-12 col-md-8 col-lg-9 col-xl-10">
            <h1 class="m-2">Bienvenido a tu sesión {{ user.first_name }}</h1>
            <h3 class="m-2">Revisa las propiedades que tienes con nosotros.</h3>
        </div>
    </div>

    {% block landlord %}
    {% include 'm7_python/landlord.html' %}
    {% endblock landlord %}

    {% else %}

    <div class="row">
        <div class="col-12 col-md-4 col-lg-3 col-xl-2">
            <img class="img-fluid rounded" src="{{ user.picture }}" alt="{{ user.first_name }}">
        </div>
        <div class="col-12 col-md-8 col-lg-9 col-xl-10">
            <h1 class="m-2">Bienvenido a tu sesión {{ user.first_name }}</h1>
            <h3 class="m-2">Disfruta de nuestras ofertas de miedo.</h3>
        </div>
    </div>

    {% block renter %}
    {% include 'm7_python/renter.html' %}
    {% endblock renter %}
    
    {% endif %}
    
{% else %}
    <h1 class="m-2">No tienes acceso a este contenido.</h1>
    <h3 class="m-2">Regístrate o inicia tu sesión.</h1>
    {% endif %}
</main>
{% endblock main %}

mysite/m7_python/templates/m7_python/footer.html
<footer class="container py-2">
    <div class="text-center py-2">
        <p class="fs-3 my-auto">Creado por Néstor Patricio - 2022</p>
    </div>
    <div class="mx-2 mx-md-4 mx-xl-5 pb-2 text-center display-6">
        <a href="https://www.linkedin.com/in/nestor-patricio-rojas-rios/"
            target="_blank" class="mx-2 links" data-bs-toggle="tooltip"
            data-bs-placement="left" title="Néstor Patricio's LinkedIn">
            <i class="fa-brands fa-linkedin links"></i>
        </a>
        <a href="https://github.com/NestorPatricio"
            target="_blank" class="mx-2 links" data-bs-toggle="tooltip"
            data-bs-placement="right" title="Néstor Patricio's GitHub">
            <i class="fa-brands fa-github-square links"></i>
        </a>
    </div>
</footer>

mysite/m7_python/templates/m7_python/header.html
{% load static %}
<header class="container">
    <div class="text-center">
        <div class="d-inline-block">
            <img class="main-img d-inline" src="{% static './m7_python/img/haunted_house.png' %}" alt="Aretun">
        </div>
        <div class="d-inline-block align-middle">
            <h1 class="aretun display-1">HauntedHouses</h1>
        </div>
    </div>  
</header>

mysite/m7_python/templates/m7_python/index.html
{% extends 'm7_python/base.html' %}
{% load static %}

{% block main %}
<main class="container my-3 text-center">
    <img class="img-fluid rounded" src="{% static './m7_python/img/haunted-house-colorado-ii.jpg' %}" alt="HountedHouses">
    <h1 class="mt-4">Las casas más <b>embrujadas</b>, los departamentos más <b>creepy</b>...</h1>
    <h4 class="mb-4">Ven a ver nuestros precios de <b>miedo</b>.</h4>
</main>
{% endblock main %}

mysite/m7_python/templates/m7_python/landlord.html
{% if checker %}

<div class="my-3">
    {% for property in properties %}
    <div class="my-3">
        <div class="p-2 shadow-lg rounded message">
            <h3 class="">{{ property.name }}</h3>
            <h4 class="">{{ property.description }}</h4>
        </div>
        <div class="col-12 col-md-12 mx-auto">
            <a role="submit" class="btn btn-haunted-small m-2 fs-5" href="/update_prop?id={{ property.id }}">Editar</a>
            <button class="btn btn-haunted-small m-2 fs-5" type="button" data-bs-target="#property{{ property.id }}" data-bs-toggle="modal">
                Eliminar
            </button>
        </div>
    </div>

<!-- Modal -->
    <div class="modal fade" id="property{{ property.id }}" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content message">
                <div class="text-center m-2 btn-haunted fs-1">
                VADE RETRO SATANAS
                    <p class="fs-3 my-2">¿Estás seguro que quieres eliminar esta propiedad?</p>
                </div>
                <div class="m-2">
                    <h5 class="modal-title fs-3 text-center" id="staticBackdropLabel">{{ property.name }}</h5>
                </div>
                <div class="modal-body fs-5">
                    <div class="my-2">
                        {{ property.description }}
                    </div>
                    <div class="my-2">
                        - {{ property.tipo_inmueble.property_type }} de {{ property.terrain_sqm }} m2, con {{ property.builded_sqm }} m2 construidos. <br>
                        - Habitaciones: {{ property.rooms }}. <br>
                        - Baños: {{ property.bathrooms }}. <br> 
                        - Estacionamientos: {{ property.parkings }}. <br>
                        - Ubicación: {{ property.adress }}, {{ property.comuna.municipality }}, {{ property.region.region }}.
                    </div>
                    <div class="my-2">
                        - Arrendatario: {{ property.user.first_name }} {{ property.user.last_name }}. <br>
                        - Arriendo mensual: ${{ property.rent_price }}.
                    </div>
                </div>
                <div class="mb-4 mx-auto">
                    <a role="submit" class="btn btn-haunted-small mx-2" href="/delete_prop?id={{ property.id }}">Eliminar esta propiedad</a>
                    <button type="button" class="btn btn-haunted-small mx-2" data-bs-dismiss="modal">Cancelar</button>
                </div>
            </div>
        </div>
    </div>
    
    {% endfor %}
</div>

{% else %}

<div class="text-center">
    <h1>Aún no tienes propiedades inscritas.</h1>
</div>

{% endif %}

<div class="my-3 text-center">
    <a role="submit" class="btn btn-haunted my-2 fs-4" href="{% url 'm7_python:agrégala' %}">Agrega una propiedad</a>
</div>

mysite/m7_python/templates/m7_python/nav.html
<nav class="container">
    <div class="navbar navbar-expand-lg navbar-dark">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item mx-3 my-1">
                        <a class="links fs-4" aria-current="page" href="{% url 'm7_python:principal' %}">Inicio</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item mx-3 my-1">
                        <a class="links fs-4" aria-current="page" href="{% url 'm7_python:panel' %}">Panel</a>
                    </li>
                    <li class="nav-item mx-3 my-1">
                        <a class="links fs-4" aria-current="page" href="{% url 'm7_python:actualizarse' %}">Actualízate</a>
                    </li>
                    <li class="nav-item mx-3 my-1">
                        <a class="links fs-4" aria-current="page" href="{% url 'm7_python:cerrar' %}">Vuelve pronto</a>
                    </li>
                    {% else %}
                    <li class="nav-item mx-3 my-1">
                        <a class="links fs-4" aria-current="page" href="{% url 'm7_python:iniciar' %}">Inicia sesión</a>
                    </li>
                    <li class="nav-item mx-3 my-1">
                        <a class="links fs-4" aria-current="page" href="{% url 'm7_python:registrarse' %}">Regístrate</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</nav>

mysite/m7_python/templates/m7_python/renter.html
{% if checker %}

<div class="my-4">
    {% for property in properties %}
    <div class="my-4">
        <div href="#" role="submit">
            <button class="p-2 shadow-lg rounded message text-start" type="button" data-bs-target="#property{{ property.id }}" data-bs-toggle="modal">
                <h3 class="">{{ property.name }}</h3>
                <h4 class="">{{ property.description }}</h4>
            </button>
        </div>
    </div>

<!-- Modal -->
    <div class="modal fade" id="property{{ property.id }}" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content message">
                <div class="m-2">
                    <h5 class="modal-title fs-3 text-center" id="staticBackdropLabel">{{ property.name }}</h5>
                </div>
                <div class="modal-body fs-5">
                    <div class="my-2">
                        {{ property.description }}
                    </div>
                    <div class="my-2">
                        - {{ property.tipo_inmueble.property_type }} de {{ property.terrain_sqm }} m2, con {{ property.builded_sqm }} m2 construidos. <br>
                        - Habitaciones: {{ property.rooms }}. <br>
                        - Baños: {{ property.bathrooms }}. <br> 
                        - Estacionamientos: {{ property.parkings }}. <br>
                        - Ubicación: {{ property.adress }}, {{ property.comuna.municipality }}, {{ property.region.region }}.
                    </div>
                    <div class="my-2">
                        - Arrendatario: {{ property.user.first_name }} {{ property.user.last_name }}. <br>
                        - Arriendo mensual: ${{ property.rent_price }}.
                    </div>
                </div>
                <div class="mb-4 mx-auto">
                    <a role="submit" class="btn btn-haunted-small mx-2" href="#">Solicitar información</a>
                    <button type="button" class="btn btn-haunted-small mx-2" data-bs-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>

    {% endfor %}
</div>

{% else %}

<div class="my-3">
    <h1>Estamos preparando algo especial para ti.</h1>
</div>

{% endif %}